// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7KHIVzc6hP_WomLx-oa8siMBVjMe1rrc',
    appId: '1:113833696760:web:5a9f3c8a0e8e7c7d860a0d',
    messagingSenderId: '113833696760',
    projectId: 'promo-ecommerce001',
    authDomain: 'promo-ecommerce001.firebaseapp.com',
    storageBucket: 'promo-ecommerce001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTaYmT7nHj6mMCnIFxyLHGYyxU0iTdkRw',
    appId: '1:113833696760:android:cbc97f79dd8780ae860a0d',
    messagingSenderId: '113833696760',
    projectId: 'promo-ecommerce001',
    storageBucket: 'promo-ecommerce001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKl7laVZ4dOyjt10qk8Ae2qs801I86rYY',
    appId: '1:113833696760:ios:5096463654abd5e8860a0d',
    messagingSenderId: '113833696760',
    projectId: 'promo-ecommerce001',
    storageBucket: 'promo-ecommerce001.firebasestorage.app',
    iosBundleId: 'com.example.promoEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKl7laVZ4dOyjt10qk8Ae2qs801I86rYY',
    appId: '1:113833696760:ios:5096463654abd5e8860a0d',
    messagingSenderId: '113833696760',
    projectId: 'promo-ecommerce001',
    storageBucket: 'promo-ecommerce001.firebasestorage.app',
    iosBundleId: 'com.example.promoEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7KHIVzc6hP_WomLx-oa8siMBVjMe1rrc',
    appId: '1:113833696760:web:2b1409ebf621ab80860a0d',
    messagingSenderId: '113833696760',
    projectId: 'promo-ecommerce001',
    authDomain: 'promo-ecommerce001.firebaseapp.com',
    storageBucket: 'promo-ecommerce001.firebasestorage.app',
  );
}
